version: "3.9"

services:
  # PostgreSQL database
  database:
    image: postgres:15
    container_name: rs_bernaldo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${DB_DATABASE:-rs_bernaldo}"
      POSTGRES_USER: "${DB_USERNAME:-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  # Nginx web server
  web_server:
    build:
      context: .
      dockerfile: docker/web_server.dockerfile
    container_name: rs_bernaldo_nginx
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "8000:80"
    networks:
      - app-network

  # Laravel backend (PHP-FPM)
  backend:
    build:
      context: .
      dockerfile: docker/backend.dockerfile
    container_name: rs_bernaldo_backend
    working_dir: /var/www
    entrypoint: sh -c "php artisan migrate && php artisan db:seed && php-fpm"
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
    networks:
      - app-network

  # Nuxt.js frontend
  frontend:
    container_name: rs_bernaldo_frontend
    build:
      context: .
      dockerfile: docker/frontend.dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Docker Volumes
volumes:
  dbdata:
    driver: local
